from enum import Enum

class PurchaseTypeEnums(Enum):
    PO_CREATE="PO_CREATE"
    PO_UPDATE="PO_UPDATE"
    DIRECT="DIRECT"
    PRODUCTION="PRODUCTION"


class PurchaseViewsEnums(Enum):
    PO_VIEW="PO_VIEW"
    PURCHASE_VIEW="PURCHASE_VIEW"
    STOCKADJUSTMENT_VIEW="STOCKADJUSTMENT_VIEW"
